const line_1 = document.getElementById('string-3')
const line_2 = document.getElementById('string-5')
const line_3 = document.getElementById('string-2')
const line_4 = document.getElementById('string-6')
const line_5 = document.getElementById('string-4')
const line_6 = document.getElementById('string-1')
console.log(line_1)
console.log(line_2)
console.log(line_3)
console.log(line_4)
console.log(line_5)
console.log(line_6)